# Manipulation  des tableaux avec avec la bibliotheque numpy :

#  - Concatenate 
#  -  hstack 
#  - vstack 
#  - Reshape 
# - Squeeze 
# - Ravel

In [3]:
import numpy as np

In [7]:
A = np.zeros((4,3)) # on cree un tableau de 0 de dimension (4,3)
B = np.ones((4,3))   # on cree un tableau de 1 dimension (4,3) 

In [8]:
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
print(B)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#  hstack  
on va assembler ces deux tableaux
de facon horizontale 

In [14]:
c = np.hstack((A,B))

In [15]:
print(c)

[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]


In [16]:
c.shape

(4, 6)

#  vstack 
on va assembler ces deux tableaux
de facon verticale 

In [17]:
d = np.vstack((A,B))

In [18]:
print(d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
d.shape

(8, 3)

# Concatenate

elle permet d'assembler deux tableaux tout fois en laissant le choix de l'axe dans laquelle l'assemblage va s'effectuer

In [22]:
e = np.concatenate((A,B) , axis = 0) ## axis = 0 pour l'axe verticale

In [23]:
print(e)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [44]:
f = np.concatenate((A,B) , axis = 1) ## axis =1 pour l'axe horizontale

In [25]:
print(f)

[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]


#  reshape

elle  permet de remanipuler la forme d'un tableau pour lui donner une nouvelle forme


In [32]:
print(f.shape)

(4, 6)


In [36]:
ff = f.reshape( 6,4)
ff

array([[0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 1., 1., 1.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 1., 1., 1.]])

In [35]:
print(ff.shape)

(6, 4)


# Ravel

elle permet d'aplatir un tableau a  une seule dimension

In [37]:
f.ravel()

array([0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 1.,
       1., 0., 0., 0., 1., 1., 1.])

In [38]:
f.ravel().shape  # verification

(24,)

# Squeeze

elle a  pour effet de faire disparaitre les dimensions dans lequel on a seulement 1

In [42]:
d = np.ones((3,1))
d.squeeze()

array([1., 1., 1.])

In [43]:
d.squeeze().shape

(3,)